### PR TITLE
Add RFC for delete / load interface in ROS.

### PR DESCRIPTION
**Pull request by MichaelGrupp**
[rendered version](https://github.com/MichaelGrupp/rfcs/blob/hotswap-ros/text/0029-delete-load-in-cartographer-ros.md)

[work in progress progress implementation](https://github.com/magazino/cartographer_ros/commit/d6876c71fd89bdd762291af950581b910552622b)

### CODE REVIEW

**Comment by nwotero** [comment]
Is there a reason you can only delete finished or frozen trajectories? Can't deleting an active trajectory also finish the trajectory before deleting it for convenience?

**Comment by MichaelGrupp** [comment]
`PoseGraph.DeleteTrajectory()` just expects these states: https://github.com/googlecartographer/cartographer/blob/master/cartographer/mapping/internal/2d/pose_graph_2d.cc#L599

Could be of course changed to finish implicitly in the service handler.

**Comment by Roboterbastler** [comment]
@MichaelGrupp First, thanks for your work and sharing your WIP code! I'm trying to use and test it, but as soon as I attempt to delete a (in my case frozen) trajectory the following check fails and cartographer crashes:

```
optimization_problem_3d.cc:371] Check failed: imu_data_.HasTrajectory(trajectory_id)
```

Any idea what is going wrong?

**Comment by gurbain** [comment]
Hi everyone,

Is anyone still working on this RFC? I'm quite interested to see in integrated in cartographer-ros :)

Gabriel

**Comment by MichaelGrupp** [comment]
I plan to integrate this feature, but this might take some time since we are currently busy with other maintenance tasks.

**Comment by MichaelGrupp** [comment]
@bochen87 @wohe Can we merge this RFC for completeness? I want to upstream this feature and associated patches (see e.g. https://github.com/cartographer-project/cartographer/pull/1767 or https://github.com/cartographer-project/cartographer_ros/pull/1540).

**Review by wohe — APPROVED** [review]

**Comment by wohe** [comment]
@MichaelGrupp Could you assign an RFC number and sign off the PR?

**Comment by MichaelGrupp** [comment]
Done. I guess we should ignore or deactivate the CLA check here.

**Comment by wohe** [comment]
Changed it from CLA to DCO check.

**Pull request merged**
