### PR TITLE
Document ground truth features

### PR DESCRIPTION
**Pull request by MichaelGrupp**
[Rendered version](https://github.com/MichaelGrupp/rfcs/blob/document-ground-truth/text/0010-document-groundtruth-features.md)

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
Side note: I wanted to do something similar for internal purposes anyway, but if the RFC is fine I can create a PR for that.

**Review by gaschler — APPROVED** [review]
Adding helpful documentation is always nice.
When you document this feature, also explain its limitations to avoid misunderstandings what "ground truth" is meant here.
Thanks for pushing this forward.

**Comment by MichaelGrupp** [comment]
Cool, I have two questions:

* I guess the document format should be .rst?
* And should this go into [cartographer/docs](https://github.com/googlecartographer/cartographer/tree/master/docs) or [cartographer_ros/docs](https://github.com/googlecartographer/cartographer_ros/tree/master/docs)? Technically, the code is independent of `cartographer_ros`, so for me it makes sense to put it in `cartographer` and to add a link in the tuning guide of `cartographer_ros`.

**Comment by gaschler** [comment]
Right, .rst is our documentation format.
I'd also put it in cartographer and link it from the tuning guide.
@wohe, you agree?

**Comment by wohe** [comment]
Yes, I agree for exactly the reason you mentioned: The tools are useful independently of Cartographer ROS.

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by MichaelGrupp** [comment]
merge bot not working?

**Pull request merged**
